import type { Metadata } from "next";
import { LXGW_WenKai_TC } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import KeyPressNavigation from "@/components/KeyPressNav";

const wenkaiFont = LXGW_WenKai_TC({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${wenkaiFont.className} antialiased bg-background text-secondary min-h-screen`}
      >
        <KeyPressNavigation>
          <div className="flex flex-row">
            <div className="sticky top-0 w-[240px] h-screen border-r border-brd bg-accent">
              <Navbar />
            </div>
            <div className="flex-1 overflow-y-auto max-w-[1080px] mx-auto">
              {children}
            </div>
          </div>
        </KeyPressNavigation>
      </body>
    </html>
  );
}
